// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"solid-task-management/internal/db"
	"solid-task-management/internal/handler"
	"solid-task-management/internal/mongoose"
	"solid-task-management/internal/server"
	"solid-task-management/internal/service/task"
)

// Injectors from wire.go:

func InitializeServer() (*server.Server, error) {
	database := db.ConnectMongo()
	taskRepository := mongoose.TaskRepositoryProvider(database)
	service := task.TaskServiceProvider(taskRepository)
	taskHandler := handler.TaskHandlerProvider(service)
	handlerRegistry := handler.HandlerRegistryProvider(taskHandler)
	serverServer := server.NewServer(handlerRegistry)
	return serverServer, nil
}
